Add CLI option --display-format
devopshq/artifactory-cleanup pull request #144
Opened 2024-06-26 19:27 UTC by christianwaldmann

### What does this PR do?
- This adds the CLI option `--display-format` to customize the printed message when deleting a file

### Motivation
- I want to be able to customize the printed message when deleting files, so I can include the files' hash in there. This information can be helpful for recovering accidentally deleted files later on, as Artifactory uses [Checksum-based Storage](https://jfrog.com/help/r/jfrog-installation-setup-documentation/checksum-based-storage).

### More
- [x] Added tests

### Additional Notes
My main motivation for this PR is to include the file hash, but this option could also be useful for other use cases.

2024-06-27 07:07 UTC, allburov requested changes
Let's add it by default if there's sha1 from artifactory!

That would be useful for "export data" as well

2024-06-27 17:59 UTC, christianwaldmann commented
Changed the default to include the sha1 hash.

I'm not sure what you mean by "export data", because the option `--output` is only printing the summary and not the deleted files. Therefore a hash doesn't make sense there.

2024-06-28 02:50 UTC, allburov commented
> Changed the default to include the sha1 hash.

Oh, sorry, I meant only that, without any additional changes. 

I don't see the point of having flex format if we manually `replace` it later.

> --output is only printing the summary and not the deleted files. Therefore a hash doesn't make sense there.

I thought it was merged already, but it's not. Never mind!
https://github.com/devopshq/artifactory-cleanup/pull/136

2024-06-28 06:40 UTC, christianwaldmann commented
Got it, a fixed format including the hash works fine for me too.

I updated the PR and description accordingly.

2024-06-28 11:29 UTC, merged

2024-06-28 11:29 UTC, allburov commented
@christianwaldmann Thank you! :hugs: