Add Dockerfile
devopshq/artifactory-cleanup pull request #16
Opened 2020-10-07 19:45 UTC by TJM

This one was not quite as simple, as noted elsewhere (#15), this is not `pip install`(able). 

This "works" but should probably be switched to a more release friendly version. Right now `--version` reports version is not set.

```bash
$ docker run devopshq/artifactory-cleanup --version
artifactory-cleanup (version not set)
```

2020-10-08 05:22 UTC, allburov commented
Yep, definitely, it won't be ease.

Could you add "how to use rules in docker" to the README.md? There'll be one more file with rules (aka `rules.py`) - how must we include it, via docker volumes? `docker -v /path/to/rules.py` or something like this.

2020-10-08 13:52 UTC, TJM commented
Good idea! I am also working on a sort of "helm chart" for it. I think we can provide the "rules" via ConfigMap.. but sticking to a "docker only" solution, you could either build a new custom docker image (FROM devopshq/artifactory-cleanup) with your rules embedded or mount your rules as a volume.

2022-02-14 09:26 UTC, DrackThor requested changes
let's use an ARG for the verion:
`
ARG version=set_me
`

maybe we can add some descriptive labels like "author/maintainer", "version", "description"?

`
LABEL AUTHOR="abc"
LABEL VERSION=$version
`

since we now have a pypi package, probably rather switch to installing the package?

`
pip3 install artifactory-cleanup==$version
`

2022-02-14 09:28 UTC, DrackThor commented
> Good idea! I am also working on a sort of "helm chart" for it. I think we can provide the "rules" via ConfigMap.. but sticking to a "docker only" solution, you could either build a new custom docker image (FROM devopshq/artifactory-cleanup) with your rules embedded or mount your rules as a volume.

I think mounting rules as a volume (or ConfigMap on K8s) is a very good idea!
Did you create a branch for the HELM chart? maybe I could contribute/help as well :)

2022-02-14 17:49 UTC, TJM commented
@DrackThor  Our customer is actually running it as a Jenkins job. Jenkins mounts the "workspace" (git repo) with their rules as a volume in the pod. We are not actually running it "directly" in Kubernetes. I do think a configmap would provide a good integration point. I am thinking, in order to run it natively in K8s, it would have to run as a "CronJob" or you may have to wrap something else around it for scheduling.

2022-02-15 06:48 UTC, DrackThor commented
@TJM CronJob sounds good to me! How about writing the Dockerfile in a way that it expects the rules in some pre-defined directory. This we could then use to mount either docker volumes, the git-repo for your jenkins job or K8s configMaps. We could then create a HELM chart that creates a CronJob and a ConfigMap with the rules. The rules itself we could just have as an entry in the HELM chart values.yaml.
This way we could satisfy all usecases and still use a single image :)

2022-05-18 05:13 UTC, allburov commented
https://hub.docker.com/repository/docker/devopshq/artifactory-cleanup

2022-05-18 05:13 UTC, closed without merging